### ISSUE TITLE
Forms Studio: Numbered list instructions has dangling number

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#100]
Relevant link: https://education.launchcode.org/intro-to-web-dev-curriculum/user-input-with-forms/studio/index.html#submit-event-handler

Text states:

1. Retrieve the selected value from the radio group. 1 Use this value to determine the action URL, based on the selected search engine.

Suggested change:

1. Retrieve the selected value from the radio group. Use this value to determine the action URL, based on the selected search engine.

**Comment by gildedgardenia** [comment]
Resolved! Thanks for letting us know!
