### ISSUE TITLE
Fetching Data references Internet Explorer in a warning

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#101]
Relevant link: https://education.launchcode.org/intro-to-web-dev-curriculum/fetch/reading/fetching-data/index.html

Text: Before going through the fetch examples, please know that fetch does NOT work in Internet Explorer.
![image](https://github.com/LaunchCodeEducation/intro-to-web-dev-curriculum/assets/117787417/7aef6385-966a-4fae-ab4b-5773598ab5e1)

Suggested change is removal of warning as IE is not maintained

**Comment by jwoolbright23** [comment]
addressed in pr #123
