### ISSUE TITLE
Step 5 in Fetch exercises solution code does not work

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#102]
Relevant link: https://education.launchcode.org/intro-to-web-dev-curriculum/fetch/exercises/index.html

Text states:
5. Now, what happens if we move those last lines we added to outside and after the fetch request?

Since json hasn’t been defined outside of the response.json() method yet, in order to move the template literal that uses that json variable, we’ll need to initiate it outside of the function call. Let’s also put our print statement back so we can verify that our fetch works.

Refresh the page and try this. See any data? See anything of note in the console?

Solution code:
```
window.addEventListener("load", function() {
   let json = [];
   fetch("https://handlers.education.launchcode.org/static/planets.json").then(function(response){
      response.json().then(function(json) {
         console.log(json);
      });
   });
   const destination = document.getElementById("destination");
   destination.innerHTML = `<h3>Planet ${json[0].name}</h3>`;
});
```

Running this code in browser results in error: 

fetch_planets.html:15 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at fetch_planets.html:15:59

**Comment by jwoolbright23** [comment]
Addressed this is PR #123, added a note that it should there should not be any expected output. I was not able to recreate the error you mentioned above in browser console though.
