### ISSUE TITLE
Assignment 5 directions state bundle.js file is empty when it is not. 

### ISSUE THREAD

**Issue by DelLRosa** [LaunchCodeEducation/intro-to-web-dev-curriculum#103]
Directions state that the bundle.js file should be empty, but it's not. 

> Before starting work, go ahead and check out the various files in your starter code. You may notice a file called bundle.js. This file contains no code except for a comment. Do NOT delete or edit this file.
https://education.launchcode.org/intro-to-web-dev-curriculum/assignments/launch-checklist/starter-code/index.html

Uncertain if this is important, but it is causing consternation amongst students when they open the file and it is not empty. Attached an image of current bundle.js file. 
![bundle js](https://github.com/LaunchCodeEducation/intro-to-web-dev-curriculum/assets/109432194/d54b7df9-7fd4-4134-8862-5f8df8953233)

**Comment by gildedgardenia** [comment]
Resolved! Thanks for letting us know!
