### ISSUE TITLE
React Exercises Part 1 references wrong file

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#107]
Relevant link: https://education.launchcode.org/intro-to-web-dev-curriculum/react-lsn1/exercises/index.html#add-more-movies

[Support Ticket Link](https://support.launchcodelearning.org/a/tickets/26)

Text reads: "The list of movies is built using an array defined in MovieList.js."

File in code is MovieList.jsx

Suggested change reads: "The list of movies is built using an array defined in MovieList.jsx."

**Comment by johncfrauen-lc101** [comment]
Fixed and merged to main @matthewcreek. Thanks!
