### ISSUE TITLE
React Part 1 Exercises Reference TAs

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#108]
[Relevant link](https://education.launchcode.org/intro-to-web-dev-curriculum/react-lsn1/exercises/index.html#sanity-check)

[Support Ticket Link](https://support.launchcodelearning.org/a/tickets/25)

Text states: "2. Ask your TA, instructor, classmates, or Google for tips."

Suggested change: "2. Ask your IA, instructor, classmates, or Google for tips."

**Comment by johncfrauen-lc101** [comment]
@matthewcreek Fixed and merged to main. Thanks!
