### ISSUE TITLE
JavaScript in React Export Function Examples Differ

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#110]
[Relevant link](https://education.launchcode.org/intro-to-web-dev-curriculum/react-part-2/reading/js-in-react/index.html#importing-and-exporting)

[Support Ticket Link](https://support.launchcodelearning.org/a/tickets/27)

In the text the examples given are shown using the function GreetFriend. Exporting at the function definition matches the function name while exporting at the bottom uses GreetingFriend. May lead to confusion.

![image](https://github.com/LaunchCodeEducation/intro-to-web-dev-curriculum/assets/117787417/57c489ad-81f8-4536-90b0-5ecd4c492a8f)

**Comment by johncfrauen-lc101** [comment]
@matthewcreek Change implemented. Thanks for finding this!
