### ISSUE TITLE
React Part 1 Studio Mentions Incorrect Styling on Run

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#111]
[Relevant link](https://education.launchcode.org/intro-to-web-dev-curriculum/react-lsn1/studio/index.html#the-recipedescription-component)

[Support Ticket Link](https://support.launchcodelearning.org/a/tickets/28)

Text states: 10. Run your application! You should have a white screen that just includes your RecipeDescription component.

Since vite includes default styling on new projects, there's not a white screen with your content; it is either dark grey or black.

**Comment by johncfrauen-lc101** [comment]
@matthewcreek Change implemented. Thanks for catching it!
