### ISSUE TITLE
React Part 2 Exercises Typo

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#112]
[Relevant Link](https://education.launchcode.org/intro-to-web-dev-curriculum/react-part-2/exercises/index.html#part-2-buttonjsx)

Text states: Inside the Button function, create a new function called onLearnMore. This function will hold the alert method. Your method should display a message like **“Slipsh Splash”** or something related to the ocean or water.

Typo on "Splish Splash"

Suggested change: Inside the Button function, create a new function called onLearnMore. This function will hold the alert method. Your method should display a message like “Splish Splash” or something related to the ocean or water.

**Comment by johncfrauen-lc101** [comment]
Resolved by mike
