### ISSUE TITLE
React Part 2 Exercises References Starter Code that Doesn't Exist

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#113]
[Relevant link](https://education.launchcode.org/intro-to-web-dev-curriculum/react-part-2/exercises/index.html#part-3-profiles-component)

[Support Ticket Link](https://support.launchcodelearning.org/a/tickets/30)

Text states: Section B. Number 4. The starter code contains some CSS styling for the image called img. Apply the styling to the image by using the className attribute.

Referenced css file does not contain img class

![image_2024-05-03_152740677](https://github.com/LaunchCodeEducation/intro-to-web-dev-curriculum/assets/117787417/72766df4-6dc6-47a1-aebb-c92b6ab0abaa)

**Comment by johncfrauen-lc101** [comment]
Fix implemented
