### ISSUE TITLE
React Part 2 Studio Starter Code Preventing Component Render

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#114]
[Relevant Link] (https://education.launchcode.org/intro-to-web-dev-curriculum/react-part-2/studio/index.html#part-1-ratearecipe)

Part 1 and 2 of the Studio references looking at your browser to see renderings change based on props passed into functional components. This is misleading because an error in the starter code prevents rendering of any functional components until Part 3 requires you to change the problem code. 

![image](https://github.com/LaunchCodeEducation/intro-to-web-dev-curriculum/assets/117787417/2fc9e831-10e6-41fa-8d78-93a967270baf)

The return statement in RecipeName.jsx does not return HTML elements so no elements are being rendered in the browser. Commenting this return statement out or changing it to an empty return will allow RateARecipe and Button to display properly.

**Comment by johncfrauen-lc101** [comment]
[Support Ticket Link](https://support.launchcodelearning.org/a/tickets/39)

**Comment by johncfrauen-lc101** [comment]
Resolved by Mike

**Comment by matthewcreek** [comment]
Hey John am I able to view the support ticket link? Just curious.

**Comment by johncfrauen-lc101** [comment]
Hey Matthew! 
I don't believe you can since it might be an admin link to the ticket. Put it on this issue so we can keep track of the ticket its related to. For any future issues, please log them using our support website: https://support.launchcodelearning.org/support/home
