### ISSUE TITLE
Assignment 6 has package lock file in gitignore preventing tests from running on github

### ISSUE THREAD

**Issue by pjduri** [LaunchCodeEducation/intro-to-web-dev-curriculum#115]
Relevant link: [https://education.launchcode.org/intro-to-web-dev-curriculum/assignments/orbit-report/index.html](url)

Starter code repo: [https://github.com/LaunchCodeEducation/orbitReport-React/blob/main/.gitignore](url)

Suggested fix:  Delete `package-lock.json` line from file.

**Comment by gildedgardenia** [comment]
Resolved! Thanks for letting us know!
