### ISSUE TITLE
Chapter 5 Logical Operators Table missing correct syntax for Logical OR

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#119]
[Relevant link](https://education.launchcode.org/intro-to-web-dev-curriculum/decisions-with-conditionals/reading/logical-operators/index.html#operator-precedence)

Text shows:
![image](https://github.com/LaunchCodeEducation/intro-to-web-dev-curriculum/assets/117787417/1351d975-3864-4095-a2ff-603d9b99bf52)

Suggested change:
Add the correct syntax to the Logical OR table row: `||`

**Comment by johncfrauen-lc101** [comment]
Resolved by Mike
