### ISSUE TITLE
Wrong heading level in example markup for Fetch and JSON studio

### ISSUE THREAD

**Issue by kmonahan** [LaunchCodeEducation/intro-to-web-dev-curriculum#127]
The markup provided for learners to use in the Fetch & JSON studio at https://education.launchcode.org/intro-to-web-dev-curriculum/fetch/studio/index.html#html-template uses `<h3>` for the heading. However, since the page only contains the `<h1>` for the title "Astronauts," those headings should be h2 to avoid skipping a heading level and introducing accessibility issues (see https://www.w3.org/WAI/tutorials/page-structure/headings/#heading-ranks)

**Comment by kmonahan** [comment]
Also just realized the img tag is missing an alt attribute. It's admittedly difficult to do a proper alt description with dynamic data coming from an API, but we could at least have them do `Headshot of ${firstName} ${lastName}`

**Comment by johncfrauen-lc101** [comment]
Resolved by Mike
