### ISSUE TITLE
Suggested improvements to Launch Checklist (Graded assignment #5) 

### ISSUE THREAD

**Issue by kmonahan** [LaunchCodeEducation/intro-to-web-dev-curriculum#128]
The starting and expected final HTML for GA5 doesn't always follow best front-end practices. In the interest of ensuring learners get practice writing code that is a bit closer to what they should be doing in a real-world scenario, would suggest making some adjustments:

- Labels should be siblings of, not parents of, the form elements and connected with `for`. https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-implicitly notes that explicit associations are better supported by assistive technology. Since this would require adding IDs to the form inputs, if the goal is to ensure learners must get elements by something other than ID, maybe a class or data attribute could be used instead of an ID for some of the launch status items.
- The images need an alt attribute. Suggestion would be to add this to the API endpoint and have the learners add that to the appropriate place. [https://sc.edu/about/offices_and_divisions/digital-accessibility/toolbox/best_pr[…]ces/alternative_text/step-by-step-instructions-alt-text/index.php](https://sc.edu/about/offices_and_divisions/digital-accessibility/toolbox/best_practices/alternative_text/step-by-step-instructions-alt-text/index.php) is one good guide I've found to writing alt text.
- An ordered list doesn't really make sense as the markup for the planetary data. Since the markup is provided as part of the assignment, this seems like a great place to use the definition list element. It doesn't get a lot of love but is designed for connecting terms and definitions or keys and values, which is exactly what's being displayed here.
- The button should have `type="submit"` as an attribute. I'm not sure that's actually required for accessibility, since if the button is inside a form, it'll default to having a type of submit anyway. However, it's required by https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/button-has-type.md and so seems like a useful thing for learners to get used to seeing, since it may become more important as they start working with React.

**Comment by johncfrauen-lc101** [comment]
[Support Ticket Link](https://support.launchcodelearning.org/a/tickets/43)

**Comment by johncfrauen-lc101** [comment]
Hello @kmonahan,

We implemented your suggestions.
Can you please review the code for GA5 and let us know if this issue is good to close?

Thanks!

Christian Frauenhoffer

**Comment by johncfrauen-lc101** [comment]
Closing this issue since the change is now implemented. Thanks again @kmonahan!
