### ISSUE TITLE
Update Create React App Instructions 

### ISSUE THREAD

**Issue by icr8FreeCode** [LaunchCodeEducation/intro-to-web-dev-curriculum#40]
# CRA - React 
[Create React App on their official documentation](https://github.com/facebook/create-react-app) (new docs updated March 2023). 

Replace Create React App with instructions using [Remix Instructions](![image](https://github.com/LaunchCodeEducation/intro-to-web-dev-curriculum/assets/109628112/4c48e394-8aa9-42aa-8e84-2dc6f71266b4)) 

![image](https://github.com/LaunchCodeEducation/intro-to-web-dev-curriculum/assets/109628112/e426ccfc-0205-4cfe-abf5-17b9af14718b)

Chapter 29 - [Create a React Application](https://education.launchcode.org/intro-to-web-dev-curriculum/react-lsn1/reading/setup/index.html)

**Comment by jwoolbright23** [comment]
See PR #72. Updated instructions creating a react app with Vite.
