### ISSUE TITLE
Note about unfamiliar code in Assignment 5

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/intro-to-web-dev-curriculum#78]
The starter code uses `async` and `await` to help events trigger in order for the autograder. The Sept. 23 class has reported that these keywords are confusing, so we can add a note highlighting that those are there for the autograder and that students do not need to learn these keywords for class.

**Comment by johncfrauen-lc101** [comment]
[Support Ticket Link](https://support.launchcodelearning.org/a/tickets/36)

**Comment by johncfrauen-lc101** [comment]
Resolved
