### ISSUE TITLE
Broken links in "Common String Methods" section of chapter 7

### ISSUE THREAD

**Issue by pjduri** [LaunchCodeEducation/intro-to-web-dev-curriculum#82]
Relevant link:
[https://education.launchcode.org/intro-to-web-dev-curriculum/stringing-characters-together/reading/string-methods/index.html#common-string-methods](url)

[Support Ticket Link](https://support.launchcodelearning.org/a/tickets/35)

Links for individual string methods go to Error page.  E.g.:
[https://education.launchcode.org/intro-to-web-dev-curriculum/stringing-characters-together/reading/string-methods/string-indexof-examples](url)

The more general W3Schools and MDN links work fine, just the ones for the method examples seem to be broken.

**Comment by johncfrauen-lc101** [comment]
Hello @pjduri, I fixed this issue in the live curriculum.

Can you please review it and confirm that it works for you?

Thanks!

Christian Frauenhoffer

**Comment by johncfrauen-lc101** [comment]
@pjduri Closing this issue as the fix is in Prod now and it's been a couple days since my last comment. Thank you again for catching this!
