### ISSUE TITLE
Typo in JavaScript Chapter 11: More on Functions

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#89]
Relevant link: https://education.launchcode.org/intro-to-web-dev-curriculum/more-on-functions/reading/functions-as-values/index.html#functions-are-objects

Typo is in second paragraph of linked section: "In particular, functions have a data type, similar too other javascript objects."

"too" is used instead of "to"

**Comment by jwoolbright23** [comment]
Addressed in PR #123
