### ISSUE TITLE
Assignment 1 Part 2 - data type conflict between variable declaration instructions and autograder expectation

### ISSUE THREAD

**Issue by pjduri** [LaunchCodeEducation/intro-to-web-dev-curriculum#90]
Relevant Link:  [https://education.launchcode.org/intro-to-web-dev-curriculum/assignments/candidate-testing/part-2/index.html](url)

Chart that shows questions and correct answers to be stored in their respective arrays has the number 3 as the final correct answer, but autograding tests expect the string "3" within the variable declaration.  The other numerical answer in the same chart is shown as a string as the autograder expects.  

![image](https://github.com/LaunchCodeEducation/intro-to-web-dev-curriculum/assets/108307350/7d0a1677-d3c3-4231-b421-d5a5926da130)

Autograder file for starter code here, relevant expect statement on line 58:
https://github.com/LaunchCodeEducation/Candidate-Testing-Autograded/blob/main/test/candidate-testing.test.js

**Comment by gildedgardenia** [comment]
Resolved! Thanks for letting us know!
