### ISSUE TITLE
Assignment 2 Unit Testing Calls for wrong function -- failing test

### ISSUE THREAD

**Issue by DelLRosa** [LaunchCodeEducation/intro-to-web-dev-curriculum#91]
https://education.launchcode.org/intro-to-web-dev-curriculum/assignments/scrabble-scorer/scoring-algorithms/index.html, 

instructions tell student to use "scoringFunction" as the key in the scoring object, while unit tests look for "scorerFunction"

**Comment by gildedgardenia** [comment]
Resolved! Thanks for letting us know!
