### ISSUE TITLE
Ch 14 Unit Testing TDD text does not match code example

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#93]
Relevant link: https://education.launchcode.org/intro-to-web-dev-curriculum/unit-testing/reading/tdd-in-action/index.html#requirement-3

Text states:
"See lines 16 - 19 to see the test added for this requirement. To test this case not.toEqual() was used, which is checking if the two values are NOT equal. not.toEqual() is used to make sure that result.id is NOT equal to undefined."

Code example:
expect(result.id).not.toBeUndefined();

Suggested change: Text references not.toBeUndefine() or code refactored to include not.toEqual()

**Comment by jwoolbright23** [comment]
Addressed this in PR #123
