### ISSUE TITLE
Mars Rover Instructions Unnecessary Step

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#94]
Relevant Link: https://education.launchcode.org/intro-to-web-dev-curriculum/assignments/mars-rover/rover-class/index.html#rover-tests

Text states:
"Create spec/rover.spec.js and write the following tests. Write the code to make them pass in rover.js. Remember to use the given phrase as the test description."

File already exists in starter code.

**Comment by jwoolbright23** [comment]
Closed with #123
