### ISSUE TITLE
HTML Me Something: 2 Autograder tests fail unless elements are specific colors despite change to instructions

### ISSUE THREAD

**Issue by Carolista** [LaunchCodeEducation/intro-to-web-dev-curriculum#95]
The instructions [here](https://education.launchcode.org/intro-to-web-dev-curriculum/assignments/html-me-something/part-2/index.html#requirements) for JS GA4 used to specify that `#mainHeading` had to be red and `.funParagraph` had to be green, but now it just says "styling of your choosing." (This is great, because previously students routinely vocalized a desire to not have garish red and green elements mucking up their otherwise very nice designs.) However, the 5th and 6th unit tests in `grading.test.js` are still checking for those colors specifically.

**Comment by gildedgardenia** [comment]
Resolved! Thanks for letting us know!
