### ISSUE TITLE
HTTP chapter hyperlink bad formatting

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/intro-to-web-dev-curriculum#97]
Relevant link: https://education.launchcode.org/intro-to-web-dev-curriculum/http/reading/how-the-internet-works/index.html#tcpip

Inside the Note reads: "You can think of the Internet as a &ldquo;series of tubes.&rdquo;"

**Comment by jwoolbright23** [comment]
Addressed in PR #123
